name: 'ansdoc'
description: 'Generate Markdown Table docs for your Ansible Role'
author: tommorelly@gmail.com

inputs:
  vars-file:
    required: true
    description: "path to your ansible vars file"
    default: "defaults/main.yml"
  output-file:
    required: true
    description: "file where to write the generated markdown table"
    default: "README.md"

runs:
  using: 'docker'
  image: "docker://ghcr.io/falcosuessgott/ansdoc:v0.0.3"
  env:
    ANSDOC_FILE: ${{ inputs.vars-file }}
    ANSDOC_INSERT: "true"
    ANSDOC_OUTPUT_FILE: ${{ inputs.output-file }}
