on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    name: ansdoc
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: ansdoc
        uses: ./
        with:
          vars-file: test/main.yml
          output-file: test/README.md
